### ISSUE TITLE
How to build jar file?

### ISSUE THREAD

**Issue by iheron** [nknorg/nkn-java-sdk#4]
I will build jar file in android studio project. How to do it? 
Need  build.gradle file , repositories and dependencies list?

**Comment by RealJohnSmith** [comment]
You can add this directly as dependency.

In gradle, add a resolver:

```
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```

and a dep itself:

```
	dependencies {
	        implementation 'com.github.nknorg:nkn-java-sdk:0.1.1'
	}
```

**Comment by iheron** [comment]
thanks
